### ISSUE TITLE
怎么这个不行啊，代码里面都是空的

### ISSUE THREAD

**Issue by Ivanlovening** [viest/php-ext-xlswriter-ide-helper#1]
怎么这个不行啊，代码里面都是空的
![image](https://user-images.githubusercontent.com/22016486/102183093-3f48c300-3ee8-11eb-931b-813916196279.png)
这是还没有完成吗？

**Comment by viest** [comment]
这个项目是 IDE Helper.............只是用于代码提示，不是包含实际逻辑，注意看项目名称！！
